name: Java CI with Maven

on:
  push:
    branches: [ "rework" ]
  pull_request:
    branches: [ "rework" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn clean package -U

      - name: Upload JAR file as artifact
        uses: actions/upload-artifact@v4
        with:
          name: PerPlayerKits
          path: target/*.jar